---

- hosts: test 
  # roles:
  #   - role: '../verygood.openvpn'

  vars_files:
    - defaults/main.yml

  tasks:
    - name: defaults
      debug: msg={{virtual_private_cidr | ipaddr('network') }}

    - debug: msg={{ ansible_default_ipv4.network  }}

    - name: do it 10.6.2.0 => + 10.6.2.128/28
      debug: msg={{ ansible_default_ipv4.network | ipsubnet(28, 0) | ipaddr('netmask') }}

    - name: do it 10.6.2.0 => + 10.6.2.128/28
      debug: msg={{ ansible_default_ipv4.network | ipsubnet(28, 0) | regex_replace('\.0/28','.128') | ipaddr('address') }}

    - name: run main
      include: tasks/main.yml
