---

- name: OpenVPN Client Keys | Generate client config
  template: src=client.ovpn.j2 dest=/etc/openvpn/{{item}}-{{openvpn_cname}}.ovpn owner=root group=root
  with_items: '{{clients}}'

- name: OpenVPN Client Keys | Fetch ca key
  fetch: src=/etc/openvpn/keys/ca.crt dest={{client_config_dest}}/{{item}}/{{openvpn_cname}}/ca.crt flat=yes
  with_items: '{{clients}}'

- name: OpenVPN Client Keys | Fetch client config
  fetch: src=/etc/openvpn/{{item}}-{{openvpn_cname}}.ovpn dest={{client_config_dest}}/{{item}}/{{openvpn_cname}}/{{openvpn_cname}}.ovpn flat=yes
  with_items: '{{clients}}'
