pip-install: &pip-install
  name: Install pip modules
  command: |
    sudo pip install setuptools --upgrade
    sudo pip install ansible==2.2.0

bundle-install: &bundle-install
  name: Install ruby gems
  command: |
    bundle install

kitchen-test: &kitchen-test
  name: kitchen test
  command: |
    kitchen test

ansible-syntax-check: &ansible-syntax-check
  name: ansible plays syntax check
  command: |
    ansible-playbook -i tests/hosts -c local tests/all.yml --syntax-check

version: 2
jobs:
  build:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: ruby:2.3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: *bundle-install
      - run: *kitchen-test
